### PR TITLE
updating minimum versions of packages because of vulnerabilities

### PR DESCRIPTION
**Pull request by jacobbullock**
I tested this out on staging as I couldn't login with googles locally.  It all seems to run fine.  We may still see the security alerts because of how it is scanning the `yarn.lock`, but I believe this addresses them

### CODE REVIEW

**Comment by jacobbullock** [comment]
the app is still running on staging, I can deploy master again, but figured someone might want to test it out on staging first.

**Comment by CodingItWrong** [comment]
@jacobbullock How is this running on staging without being merged down? If I'm remembering and reading the setup correctly, the `master` branch automatically deploys to staging:

Screen Shot 2019-06-11 at 8 21 53 AM

I don't want us to directly deploy to staging because that gets the commit and deploy history out of sync and can lead to confusion in the future, especially when we haven't touched the app for a number of months.

If there are things that prevent running the app locally we should fix those. And if you'd like an additional environment to deploy directly to we could consider setting up a dev environment.

Would more detail about deployment in the readme have prevented this misunderstanding?

Let me know your thoughts on the above—I want to make sure I understand the state of the staging environment before we merge this down.

**Comment by CodingItWrong** [comment]
We mainly have separate staging and production environments for historical reasons. @harrypritchett has having the staging environment helped with the tasks you worked on? If not, we could consider removing the staging environment entirely to keep things more simple/standard. (Or maybe turn the staging environment into a dev environment that isn't in the CI pipeline.)

**Comment by harrypritchett** [comment]
@CodingItWrong Staging has been helpful for dealing with some specific issues, ie https forwarding, that are difficult to reproduce and test in local development. I would hate to remove staging since it is already set up and providing value.

**Comment by jacobbullock** [comment]
@CodingItWrong  I think it's running fine.  I was able to login, see the videos load, and play a bunch of videos.  I Just wanted to make sure that we had other eyes on it as well. 

I didn't want to merge the code in before really seeing it work and I wasn't able to login via googles locally.  But i just didn't have time to dig into that more.  I was looking into this during NBC builds over the weekend. 

I understand the concern about deploying to staging the way I did, I didn't realize master would go there first and then you manually deploy prod when that is good.

**Comment by CodingItWrong** [comment]
@jacobbullock Gotcha, that makes sense that a security warning is urgent, and it's not necessarily possible to get things working locally. Let's merge and I'll deploy to staging! I'll wait to deploy to production until Monday when I'm around for any troubleshooting.

**Pull request merged**
